### ISSUE TITLE
[Feature Request] Scrobbling to Last.fm on Sync

### ISSUE THREAD

**Issue by MochaMage** [memen45/SubMusic#11]
Would it be possible to add a new option to enable scrobbling on sync?

**Comment by memen45** [comment]
Yes it is on the list, not directly to Last.fm, but Subsonic as well as Ampache support scrobble/ play endpoints and I believe both have integrations with Last.fm. Would that be sufficient?

**Comment by MochaMage** [comment]
That's pretty much exactly what I was thinking, I was thinking about the /scrobble endpoint in the Subsonic API but wasn't sure if Ampache had its own equivalent.

**Comment by memen45** [comment]
Great! I am implementing it right now. For Ampache I need some clarifications, so I will have to delay this feature until that issue is solved. See Ampache/Ampache#2646.

**Comment by lachlan-00** [comment]
Does submusic sync use stream or download to save tracks?

In Ampache's subsonic api:
* download does not fire plugins like last.fm.
* stream will launch all scrobble plugins.

**Comment by MochaMage** [comment]
> Does submusic sync use stream or download to save tracks?
> 
> In Ampache's subsonic api:
> 
> * download does not fire plugins like last.fm.
> * stream will launch all scrobble plugins.

I believe it uses download, based on what I've read in the code base. However, it shouldn't matter since that's why the Subsonic API spec has the /scrobble method for dealing with offline listens.

**Comment by lachlan-00** [comment]
sorry i forgot that there's Ampache API 4.2 in this app, it's actually not important then and i'll resolve the Ampache side out of this issue.

**Comment by memen45** [comment]
The app uses the stream method to retrieve the file. This is mainly because stream allows for transcoding if the server supports it. However, the files from stream are just cached, so a stream request does not mean it is played once.

**Comment by memen45** [comment]
The scrobbling functionality should be included now and will sync to your Ampache/Subsonic server during a normal sync. This is not supported on the Nextcloud music app unfortunately (owncloud/music#339), so I have not been able to test it completely. If you are able to, please test the feature and provide feedback here!

**Comment by MochaMage** [comment]
Beautiful, I'm downloading the updated version right now, will test it out once it's installed

**Comment by memen45** [comment]
The last update fixes the scrobble for Subsonic backends. I assume it is working now, but please keep me updated if it is not! Thanks a lot for your feedback!
