### ISSUE TITLE
When using headphones, the next track works as a 30 second fast forward

### ISSUE THREAD

**Issue by shady2k** [memen45/SubMusic#13]
Has installed today this application and it worked fine, but it have one annonyed issue. When I trying to control music via my headphones in standart music application double click on my headphones works as next track command, but in this application it works as fast forward on 30 seconds. Can you fix this?

**Comment by memen45** [comment]
Thanks for your feedback. I am not sure whether it is possible for me to change this behaviour. Do you have other controls on your headphone that behave differently as well? It might be the 'next track' command is actually a 'skip forward/backward' command and the native music app interprets this as a 'next track' command as it does not support skipping 30 seconds.

**Comment by shady2k** [comment]
Headphones has standart contols: one click - play/pause, double click - next track. With standart music player and with spotify app they worked as expected, but in this app double click produces fast forward.

**Comment by shady2k** [comment]
Could you compile app version for me without PLAYBACK_CONTROL_SKIP_FORWARD and PLAYBACK_CONTROL_SKIP_BACKWARD profile?

**Comment by memen45** [comment]
Well, yes I can compile it for you to sideload the app, however, the sideloaded app doesn't work properly for many features, so I am not sure if that will be a solution. 

I could open a bug report in the Garmin forums, since I think this behaviour is not expected.

**Comment by shady2k** [comment]
I thought it was difficult but was able to compile myself. I can confirm that compile without PLAYBACK_CONTROL_SKIP_FORWARD and PLAYBACK_CONTROL_SKIP_BACKWARD solved my issue.

**Comment by memen45** [comment]
In the last update (v0.1.3-delta) I made a small modification with regards to skipping tracks. Could you check if it solves your issue?

**Comment by shady2k** [comment]
> In the last update (v0.1.3-delta) I made a small modification with regards to skipping tracks. Could you check if it solves your issue?

Just cheked out the last version. Problem still persists.

**Comment by shady2k** [comment]
Maybe implement such logic: when in podcast mode use PLAYBACK_CONTROL_SKIP_FORWARD and PLAYBACK_CONTROL_SKIP_BACKWARD, when play music - without this attributes. Can it be done?

**Comment by memen45** [comment]
Yes that should be possible. I still do not know the cause of the issue, but I think 

> Podcast: skip to next episode
> Normal: fast forward 30sec

should be possible. Only thing is, the 30s skip buttons do not show up as an option on the watch if the PLAYBACK_CONTROL_SKIP_FORWARD and PLAYBACK_CONTROL_SKIP_BACKWARD are removed right?

**Comment by shady2k** [comment]
> Only thing is, the 30s skip buttons do not show up as an option on the watch if the PLAYBACK_CONTROL_SKIP_FORWARD and PLAYBACK_CONTROL_SKIP_BACKWARD are removed right?

Yes, buttons don't show.

**Comment by memen45** [comment]
Hmm, another option is to make an option somewhere to turn on or off the 30s skip. It could solve the issue for you, while still enabling other users to have the 30s skip buttons available per default. What do you think of that?

**Comment by shady2k** [comment]
Yes, it fits my needs. I never use these buttons, but I understand that there are people who need it. Adding the ability to disable these buttons in the settings is a good way to solve my issue. Please check that this setting is stored between sessions.

**Comment by memen45** [comment]
Sorry for not coming back to this. I still do not completely understand the behaviour of the watch controls vs headphone controls in all situations (e.g. while track is playing vs when paused). I think the most thorough approach would be to 
- list controls of interest (previous, next, skip forward, skip backward)
- list states of interest (playing, paused, canSkip true, canSkip false, skip enabled, skip disabled)
- record SongEvents for each combination of state and control

Based on the results, a decision can be made to make sure everything behaves as expected. The above requires some testing on an actual device, some code to allow the testing and results may still vary between devices.

For now, I have added the option in settings to disable the Skip 30s buttons (see version 0.2.1-myles). Hopefully it resolves your issue, please let me know if it does or if you encounter any problems. 
Thanks for your patience!

**Comment by memen45** [comment]
On the watch, you can go to the main menu, then choose About --> Settings, then scroll down to Enable skip and uncheck the box. You can also change the setting from the Connect IQ app settings.
