### ISSUE TITLE
Changing playlists requires watch reboot

### ISSUE THREAD

**Issue by oddomatik** [memen45/SubMusic#14]
With latest update (v0.1.1), I can no longer change playlists without a reboot of the watch. When I select a new playlist, it just restarts the current playlist. I have to reboot the watch, and then it will play the "last selected" playlist correctly, but will not change to a "newly selected" playlist without another watch reboot.

Using Sync'd playlists from Ampache. I am trying an application data reset now. Will update if that fixes.

**Comment by memen45** [comment]
Thanks for reporting! Are you talking about playback -> choose playlists or selecting playlists for sync?

**Comment by oddomatik** [comment]
Playback -> Choose Playlist.
Thanks for your attention! Happy to help collect logs or troubleshoot further if you have any requests.

**Comment by memen45** [comment]
Just checked the code and indeed the 'current playlist' is updated on app start (which apparently only happens on reboot). I will fix it tomorrow morning!

**Comment by memen45** [comment]
Let me know if the last update fixed the issue (v0.1.2-charlie) for you! Just updated in the Connect IQ store. Also added the feature to start playback from a specific song in the playlist.

**Comment by oddomatik** [comment]
Changing Playlists now seems to work without a watch reboot. Thank you **very** much!

**Comment by memen45** [comment]
Thanks a lot for your feedback and great to hear it is working now!
