### ISSUE TITLE
Endless loop when not wifi network found

### ISSUE THREAD

**Issue by LORANDITSUM** [memen45/SubMusic#18]
When trying to sync if me wifi is present. The app only show try again option but cannot exit the the retry. So unless wifi connection is successful you must restart the device

**Comment by memen45** [comment]
Thanks for your feedback! Do you have a screenshot? I do not remember that I built such a screen, so it might be Garmin built-in. Do you have a physical 'back' button? It might allow you to exit either on the 'try again' screen, or the wifi  searching screen.
Let me know your findings!

**Comment by LORANDITSUM** [comment]
If I'll get it again I'll sceenshot it. I am using the forrunner 645 music. But none of the button did anything. It's also get stuck on searching for wifi screen. But I made a successful server test just before. 

It's might be waiting for a callback or something


By the way I was wondering how are you compiling and testing your code ?

**Comment by LORANDITSUM** [comment]
![IMG_20210130_203026](https://user-images.githubusercontent.com/4907830/106364761-28481e00-633a-11eb-87d0-24c45e5cbd19.jpg)

**Comment by memen45** [comment]
It looks like the screen is indeed from Garmin Watch itself. 

Are you connected to your phone through bluetooth? Does it make a difference to be connected with bluetooth or not?

Debugging and compilation is done through Eclipse or visual studio. Both require an add-on to be installed if you want to compile or use the simulator (see developer.garmin.com).

**Comment by LORANDITSUM** [comment]
I am connected with Bluetooth.  it doesn't seems to have any effect. i could get it to work only when i first made sure it is connected to WIFI by doing a network test and then it could sync. i guess its a garmin firmware issue

**Comment by LORANDITSUM** [comment]
I haven't dove into it yet. But I believe errors are not consumed. So once you get an error it's is repeated regardless of the state
