### ISSUE TITLE
Fail to connect Forerunner 945 to demo subsonic server.

### ISSUE THREAD

**Issue by victor-dementiev** [memen45/SubMusic#20]
SubMusic version: 0.1.5 - downloaded 2 days ago.
Device: Garmin Forerunner 945. S/W version 6.20

In order to test my Garmin connection , I use server:
```
Server: http://demo.subsonic.org
Username: android-guest
For API key - I enter the password for the demo service.
```

**Errors**
1. `Test Server` option shows me `-400 INVALID_HTTP_BODY_IN_NETWORK_RESPONSE` without connecting to my WIFI. I do verify that I can successfully sync my watch via WIFI.
2. `Sync` option connects to WIFI and shows infinite `Syncing`. I have the same problem on connecting to my local subsonic service with 1 song media file.
3. It looks like `Sync` option keeps open WIFI connection and in this case `Test Server` option shows me ERROR::HTTP::404 NOT_FOUND.
4. After watch restart and select `Test Server` option with disabled bluetooth I got '- 104 BLE_CONNECTION_UNAVAILABLE'. Why it tries to use bluetooth in stead of WIFI?

**Comment by victor-dementiev** [comment]
@memen45 Please review errors listed in this ticket.

**Comment by memen45** [comment]
Are you able to open the sync menu from the watch menu on your device? So from settings -> music providers- -> SubMusic -> Sync.

This flow should use the deprecated sync methods and it looks like your device is one of the devices that has some trouble with the new sync method. I created a bug ticket in [the Garmin forum](https://forums.garmin.com/developer/connect-iq/i/bug-reports/bug-media-communications-syncdelegate-blocks-charging) regarding a related problem. It seems that bluetooth connection is required on some devices, even though that should not be the case.

**Comment by victor-dementiev** [comment]
> Are you able to open the sync menu ...
Yes, I able to do that without any success.

**Comment by victor-dementiev** [comment]
Will attach videos of errors soon.

**Comment by memen45** [comment]
Do you see difference in behaviour for the three possible flows to initiate sync?

1. Watch settings -> Music providers -> SubMusic -> Sync
2. Music player -> choose playback icon -> More... -> Sync
3. Automated start e.g. during charge

**Comment by victor-dementiev** [comment]
1. Connects to wifi. Shows endless "Syncing".
2. Connects to wifi. Shows endless "Syncing".
3. Not sure how I can reproduce this case. Can you please advice?

Hope this help.

**Comment by memen45** [comment]
It should start automatically somewhere during charge. I do not think it can be triggered manually.

If you want me to test against your server with debugging enabled, please let me know by contacting through Connect IQ -> contact developer option with login details. I can check tonight in more detail.

Btw: did you try and use an account without the hyphen in it? Maybe something is going wrong there, not sure.

**Comment by memen45** [comment]
SubMusic app was updated (0.1.6-golf). It covers and fixes some of the crashes that were reported. Does updating change your issue?

**Comment by memen45** [comment]
Just tested in the simulator and the only API call that seems to work on the demo server seems to be the version check. In SubMusic menu -> More... -> More Info -> Server (show server settings). Here the server version should show. The error I get is -402 - Response is too large. When I try in the browser, I get a json object with 230 playlists, so yes that might be exceeding the Garmin Watch response size limits.

If you install your own instance of either AirSonic/Subsonic/Ampache you will be able to connect and sync your playlists. For Ampache you will have unlimited number of playlists, since it will be requested in parts. Subsonic/Airsonic servers so not support that, so you are limited there with regards to number of playlists and number of songs on a single playlist.

**Comment by victor-dementiev** [comment]
Possible this is new version you released, but SubMusic can connect to my local AirSonic server running on docker.
Testing now and will be back with the feedback.

**Comment by victor-dementiev** [comment]
Manage to connect to server. Test succeeded. Subsonic Version 1.15.0. Thanks for the new version !!!

Still experience the following problems:
1. Only the first file from the playlist is able to sync into watch. The sync process itself stops on 0%.
2. WiFi re-connection problem. Fail to re-connect to WiFi after failed syncing or sometimes after long 0% syncing.

Will investigate more with other servers.


Test results:
1. Connected to my local server. 

4.
