### ISSUE TITLE
300 network request time_out

### ISSUE THREAD

**Issue by cristianpb** [memen45/SubMusic#22]
Hi,

I have my own local airsonic server which I use to synchronize music with my phone using audinaut app. 

I just obtained a fenix 6s pro and I tried to do the same with your app but I have the following error:

```
300 network request time_out
```

I use a url like: `http://192.168.0.1/airsonic`, but I think the problem should be linked with connection to the server, because I don't see any request in my reverse proxy.

Do you have any idea how to debug ?

(BTW: thanks a lot for developing this app!)

**Comment by memen45** [comment]
Sounds like a network issue. Is the url the same as you use in the browser? Is the url accessible from other devices that are on the same network as the Garmin Watch?

**Comment by cristianpb** [comment]
The same url on my phone leads me to airsonic authentification page.
The phone is connected to the same network

**Comment by memen45** [comment]
I have received more problems like this. Mostly related to custom port numbers (80 and 443 are the only supported), or I have not received enough details on the problem. 

Can you try against an online demo server of airsonic/subsonic? Do you get the same error?

**Comment by cristianpb** [comment]
I tried http://demo.subsonic.org on the fenix 6 and got the same response.
I double checked the same url, username and password in my browser and it works.

I tough that maybe wifi didn't worked as expected but for other things such as updates it works, I also tested a podcast music source and I'm able to fetch content but I got a warning because of battery below 50% when I want to sync. I will test tomorrow with full battery

**Comment by cristianpb** [comment]
I tested with 100% battery and I have the same error 300 using SubMusic with the online demo server from subsonic.

I think that the problem is not with the wifi because I'm able to download podcast using other sources like runcast.

**Comment by memen45** [comment]
Are you connected with your phone through bluetooth? And do you get this same -300 network request timeout error on all possible networking options, i.e. Test Server, Server Info, Select playlists, Sync?

**Comment by memen45** [comment]
Did you try to change backend to ampache and try against an Ampache (demo) server? Checking this could isolate the problem for me to either backend related or device related. I am a bit at a loss currently as to what could be the cause.

**Comment by cristianpb** [comment]
I have my phone connected with Bluetooth. I have the message "300 network request timeout" with Test Server, Server Info. Fpr Sync it just don't stop. 

However, server tests are OK for Ampache demo server!

**Comment by cristianpb** [comment]
I just updated to version 0.1.7-hotel and I have the same message "300 network request timeout"

**Comment by memen45** [comment]
I have literally no idea what could be the cause. The requests are the same for Ampache and Subsonic, so there should be no reason why one fails and the other works.

Where did you find a demo server for subsonic/airsonic?

**Comment by cristianpb** [comment]
I know is difficult to debug without having more detailed logs. Do you know how can I provide more details about the problem ?

I saw that the subsonic server use http and the ampache server use https. I don't know if that make the difference.

I use the sample server from http://demo.subsonic.org
The account details can be found at the [audinaut repository](https://github.com/nvllsvm/Audinaut/blob/79ea6cb082fcaa1eb32c2f3f4ed4c4b11423832d/app/src/main/java/net/nullsum/audinaut/activity/SubsonicFragmentActivity.java#L585)

**Comment by memen45** [comment]
Can you try against this one: https://demo.navidrome.org
User: demo
Key: demo

It is a demo for some other project, but also providing subsonic backend with https. 

Well, main problem at the moment is that I cannot reproduce the issue, so it is very hard to debug. There might be https requirements, but there should be a separate error code for it and as far as I know, most devices should work fine with http as well.

**Comment by memen45** [comment]
> I use the sample server from http://demo.subsonic.org
> The account details can be found at the [audinaut repository](https://github.com/nvllsvm/Audinaut/blob/79ea6cb082fcaa1eb32c2f3f4ed4c4b11423832d/app/src/main/java/net/nullsum/audinaut/activity/SubsonicFragmentActivity.java#L585)

Just tested and works fine in the simulator.

**Comment by cristianpb** [comment]
The demo from https://demo.navidrome.org works fine for me.

However, the demo from http://demo.subsonic.org still have the error 300 "Network_request_time_out"

I'm thinking that maybe it's related with backend api, I will try to deploy a local nextcloud to share my files

**Comment by memen45** [comment]
A similar [report](https://forums.garmin.com/developer/connect-iq/f/discussion/166139/error--300) on the Garmin developer forum. It seems like some devices are requiring https connection. This could be due to the Garmin Connect Mobile version and operating system (iOS is more strict than Android).

The documentation states a -1001 error indicates https requirements, but as the report states, in practice it results in a -300 network timeout.

Unfortunately, as a developer I cannot circumvent these limitations. I would recommend using https on your site if possible. I should note that self-signed certificates are also not supported on Garmin watches.
