### ISSUE TITLE
SubMusic crashes on Venu 2S

### ISSUE THREAD

**Issue by neuhausf** [memen45/SubMusic#24]
I receive a "Media error occured" (in german: "Medienfehler") upon opening SubMusic on the watch.

I cannot open SubMusic on a Venu 2S:
- Venu 2S, Firmware 3.24, Wi-Fi-Version 3.00, Connect IQ 4.0.0, TSC Version 17.36
- Language: German
- SubMusic Version: 0.1.8-india

I intend to use SubMusic with Ampache. But it doesn't matter if I configure a server address and credentials. No matter what I type, the app doesn't open: "Medienfehler".
I already tried uninstalling/reinstalling the app and restarting the watch.

**Comment by memen45** [comment]
Can you access the menu? This error might occur in case there aren't any songs downloaded and the watch still tries to load a song. 

If you can access the sync menu, you can select your playlists to sync and then the error should not occur anymore. I will check if I can find the exact cause and maybe circumvent the error.

**Comment by neuhausf** [comment]
I can‘t access any menu. As soon as I open SubMusic on the watch, I receive „Medienfehler“.

**Comment by neuhausf** [comment]
I just did that:
https://youtu.be/tXCdn7a0jR4

I also got a new version from Garmin IQ (which seems to be the automigrated one). I just reproduced the error a few times and synced the watch. Hopefully you get the logs. If not, tell my what settings I need to set.

**Comment by memen45** [comment]
Received the crash reports. It is caused on creating the menu items and I could find a bug report on the [Garmin Forum](https://forums.garmin.com/developer/connect-iq/f/discussion/255760/does-anyone-else-have-problems-pushing-menu-items-in-venu-sq/1252495#1252495) that is specifically related to your device. According to the post, it should be fixed now, so maybe you can check if there is a new software update for your watch. It might be that it is fixed in the SDK though, so if you still have the issue after software updates, let me know and I will rebuild the whole app with the latest SDK/device updates.

**Comment by neuhausf** [comment]
My watch has SDK Version 4.0.0 installed and firmware 3.24, but it finds no new updates. Is there a way to force an SDK update?

**Comment by neuhausf** [comment]
Update: I installed the beta firmware 3.34 on the watch and now I can access the menu! So I will try to configure it and see if it works.
At this point: Many thanks for your investigations 👍

**Comment by memen45** [comment]
Great to hear you got it working with the beta firmware. It will probably be fixed soon in the stable watch software as well. 

Additionally, I updated the app to make sure all the constant Strings are loaded before use, so in theory the error is fixed now for the stable software version as well. This means you can roll back to the stable version if you prefer to.

**Comment by memen45** [comment]
Note: It might take up to 2 hours for the SubMusic app to be updated, according to the Connect IQ store:
`Please note: This app has a version update pending. Changes will not be visible until the approval is complete. This process could take up to 2 hours.`
They might be rolling out the fix in their automated updates as well.
