### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by kopax-polyconseil** [memen45/SubMusic#29]
Hello,

I just got a garmin watch and found this reoo from their store.

Thanks for sharing the work, I've started to read the readme and feel like its quite complexe compare to if it wss dockerized. 

Have you ever considered Docker ? If yes, what was the issue ?

Thanks a lot !

**Comment by emeraldjava** [comment]
I believe this connect IQ docker might allow @kopax-polyconseil do what they asked for.

https://github.com/kalemena/docker-connectiq

Sorry - answer is a little late.
