### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by lemieuxl** [memen45/SubMusic#30]
Awesome watch app!

I'm having an issue with the latest version of SubMusic (0.1.15) and Ampache (4.4.3). When triggering a manual sync after a while, the sync doesn't work (it stays at 0% for a long time).

I had a look at the httpd access log, and I see multiple lines like this (multiple per seconds, then a break, and then it starts over).

```text
192.168.x.x - - [14/Sep/2021:11:41:44 -0400] "GET /ampache/server/json.server.php?date=1631494914&id=21&client=SubMusic-v0.1.15-papa&action=record_play&auth=xxxxxx HTTP/1.1" 200 103 "-" "Garmin Venu 2/4.67"
192.168.x.x - - [14/Sep/2021:11:41:44 -0400] "GET /ampache/server/json.server.php?action=handshake&user=xxxxxx&timestamp=1631634104&auth=xxxxxx HTTP/1.1" 200 512 "-" "Garmin Venu 2/4.67"
```

The test works as expected and I can list the playlists and server configuration without any issue.

It syncs correctly after uninstalling the watch app and reinstalling it (with the same parameters, username and password).

**Comment by memen45** [comment]
Seems to be an issue with authorization. What device do you have? And did you log the response bodies as well? I am curious to see if there is any error returned from the server that may be handled incorrectly.

**Comment by lemieuxl** [comment]
I only showed the httpd access logs, and it doesn't seem as if there is any (httpd) error log associated with them. I just enabled Ampache logging, and I'll update the issue next time I get the same issue (if it comes back).

**Comment by lemieuxl** [comment]
Here is the Ampache log. BTW, I'm using a Venu 2.

```text
2021-09-14T20:23:45+00:00 [ampache] (Dba) -> Database connection...
2021-09-14T20:23:45+00:00 [ampache] (Access) -> check_network rpc: ip matched ACL 192.168.x.x
2021-09-14T20:23:45+00:00 [ampache] (Api) -> Handshake Attempt, IP:192.168.x.x User:USER Version:443000
2021-09-14T20:23:45+00:00 [ampache] (Api) -> Login Attempt, IP:192.168.x.x Time: 1631651022 User:USER (2) Auth:xxxx
2021-09-14T20:23:45+00:00 [ampache] (Access) -> check_network rpc: ip matched ACL 192.168.x.x
2021-09-14T20:23:45+00:00 [ampache] (Session) -> Unable to read session from key xxxx no data found
2021-09-14T20:23:45+00:00 [ampache] (Session) -> Session created: xxxx
2021-09-14T20:23:45+00:00 [ampache] (Api) -> Login Success, passphrase matched 
2021-09-14T20:23:45+00:00 [ampache] (Dba) -> Database connection... 
2021-09-14T20:23:45+00:00 [ampache] (Access) -> check_network rpc: ip matched ACL 192.168.x.x
2021-09-14T20:23:45+00:00 [ampache] (Session) -> xxxx has been extended to Tue, 14 Sep 2021 21:23:45 +0000 extension length 3600
2021-09-14T20:23:45+00:00 [USER] (Api) -> 'user' required on record_play function call.
```

And now I get a "`BLE_QUEUE_FULL`" error when trying to show server settings and a "`GarminSdkError`" when trying to test the connection.

**Comment by memen45** [comment]
Thanks for your response! The last line in your log shows something interesting, however I would need to know the response of the server in order to see what is going wrong in the SubMusic app.

The `BLE_QUEUE_FULL` is probably due to too many requests. I will look into error handling in the ScrobbleSync tomorrow, I think I know the cause. 

It seems there is a problem in Ampache API as well, as your log states 'user' is required, while the Ampache docs state it is optional. I will check that as well tomorrow!

**Comment by memen45** [comment]
Opened an issue at ampache/ampache#3021 regarding the user required. Also checked ScrobbleSync and it has two failure modes:
- http error or garminsdkerror: should result in the currently synced record_play to be removed from the list.
- any other error: should result in all record_plays to be removed
As you can see, in either case, retries should not occur at all.

For your specific device I noticed several out of memory errors as well. Not sure whether it is your device actually. Do you sync lots of playlists/songs that could cause this?

**Comment by lemieuxl** [comment]
I sync one playlist containing 55 songs. The initial sync works as expected.

**Comment by memen45** [comment]
Are you able to create a temporary account for debugging purposes? I could check in the simulator whether there is something specific going wrong in your case. Let me know through the 'contact developer' option on Garmin Connect IQ SubMusic page. 

I have fixed some bugs in the new version (0.1.16-quebec), but i do not think it addresses your issue.

**Comment by lemieuxl** [comment]
Information sent via the contact developer link.

**Comment by memen45** [comment]
The new update 0.1.18-sierra should address some of the speed issues you encountered. Hopefully they are resolved sufficiently. If not, please let me know!

**Comment by lemieuxl** [comment]
At first glance, 0.1.18 seems to fix this issue (though I did not have much time to use with the app). I'll update if not the case.
Thanks!
