### ISSUE TITLE
Fenix 7 and Epix Gen 2 support

### ISSUE THREAD

**Issue by jhauh** [memen45/SubMusic#39]
The new watches are out now, and it would be nice to be able to use this great app with them. 

Would it take much work to add support for these watches? I would be willing to try it, given some pointers/guidance.

Thanks for all your work on this!

**Comment by memen45** [comment]
Thanks for bringing this to my attention! Often new devices are supported automatically, but this time I had to manually add the new devices. The new version (0.1.24-yankee) should be in the Connect IQ store shortly.
