### ISSUE TITLE
Testing server fails

### ISSUE THREAD

**Issue by muzmo** [memen45/SubMusic#40]
When trying to connect to a Synology NAS, using this package on the NAS (https://github.com/ghenry22/subsonic-synology), I get a:
Error 400 HTTP GarminSdkError INVALID_HTTP_BODY_IN_NETWORK_RESPONSE on my Garmin

I am using https, with the local network URL of my NAS server and using my admin password as the API key

**Comment by memen45** [comment]
Hi, thanks for your feedback! Can you check the url is correct? SubMusic app appends `/rest/` to the url you provide. Can you check the following url in your browser:

<your-server>/rest/ping?f=json

You should see a JSON 'subsonic-response'. If not, the url you have provided is not correct.
