### ISSUE TITLE
Bug: Venu 2 skip forward 30 seconds

### ISSUE THREAD

**Issue by Devirex** [memen45/SubMusic#43]
When track is playing “skip forward 30” function switches to the next track on my venu 2. 
If the actual track is paused  before skipping it works like expected and skips 30 seconds then track starts playing. If the track is paused again the function works again. If the track is playing the function will skip to the next track. 

Suggestion: Is it possible to implement a “pause” command when skip 30 seconds is executed just before the skip is called?

**Comment by memen45** [comment]
Thanks for creating the issue. I was not aware of this behaviour. #13 is somewhat related, with the use of headphones. 

Currently, the SKIP action is left to default behaviour, so this would be a Garmin bug. I would have to test 
- whether I can reproduce in simulator for Venu2
- whether other devices behave the same

Can you check if you have similar behaviour for e.g. the default music app? 
Do you have skip buttons on your headphone/earbuds that behave similar/different?

**Comment by Devirex** [comment]
There are some comments of users on Garmin Connect IQ who has the same issue on different apps which lets refer this to a Garmin bug. On the other hand it works when the track is paused so maybe it’s just not documented that the track has to be paused first before skipping? However I will test later with my headphones and give you the results. I really like the idea of your app, thanks for the great work!

**Comment by Devirex** [comment]
I connect my Galaxy Buds Live and the behavior in the SubMusic player is like follows:

> Pressing “Next Song” on the buds skips forward 30 seconds. 

> Pressing next song on the venu 2 skips to to the next song and resets the time stamp.

> Pressing “Skip 30 forward” on the watch skips to a “null” track (no title no timestamp) when track is playing

> Pressing “Skip 30 forward” again on the watch skips to the next track and resets timestamp 

> Pressing “Skip 30 forward” on the watch skips 30 seconds if track is paused before 

> Pressing “Skip 30 backward” on the watch skips to a “null” track (no title no timestamp) when track is playing

> Pressing “Skip 30 backward” again on the watch skips to the next track like “skip 30 forward and resets timestamp

> Pressing “Skip 30 backward” on the watch skips 30 seconds backward if track is paused before

**Comment by memen45** [comment]
| Playing | canSkip | skip enabled | press on | control       | event             |
|---------|---------|--------------|----------|---------------|-------------------|
|         | true    | true         | bud      | next song     | skip forward      |
|         | true    | true         | watch    | next song     | next              |
| true    | true    | true         | watch    | skip forward  | null (exception?) |
| false   | true    | true         | watch    | skip forward  | skip forward      |
| true    | true    | true         | watch    | skip backward | null (exception?) |
| false   | true    | true         | watch    | skip backward | skip backward     |
|         |         |              |          |               |                   |

I was able to reproduce your issues. These actions are not actively handled within the SubMusic app, so any bugs/issues arising are on Garmins side as far as I can tell. I added an option to disable the skip buttons. Hopefully this helps, please let me know if it does! See the new version 0.2.1-myles, shortly in Connect IQ app store.
