### ISSUE TITLE
Sync doesn't run, keep on "searching for a wifi network"

### ISSUE THREAD

**Issue by Jeannok** [memen45/SubMusic#50]
Previously synced without problem. The app is connected (fetching playlist etc works well). I've added some music to a playlist previously synced and wish to sync again. The new musics files are showed well in "playlist", but when I want to sync again, the app doesn't pass the "searching for a wifi network" screen. 

forerunner 245 music
up-to-date @home nextcloud

**Comment by memen45** [comment]
Thanks for your feedback! Did you setup a wifi network connection in the Garmin Connect app? Do other apps work properly with the wifi network?

**Comment by Jeannok** [comment]
Yes, I've a wifi setup working properly - your app can use it, cause I can see the new files added to the playlist, I just can sync it.

**Comment by memen45** [comment]
As long as you are in the SubMusic menus, the phone bluetooth connection is used to connect to the internet. Only when starting the sync, the watch starts the wifi module and tries to find the network as setup in the Garmin Connect app.

You can try and completely remove SubMusic data (About > Settings > Remove All Data) to verify that it is a SubMusic issue rather than wifi connection issue. Let me know your findings!

**Comment by Jeannok** [comment]
additionnaly, I found that when I run the "test server" command from the app, it blocks at 75%, with the text "Inlog OK, No podcasts"

**Comment by Jeannok** [comment]
Finally , I have the same issue after uninstall / reinstall the app.

**Comment by memen45** [comment]
Can you go to your watch settings, then Wi-Fi, then Connect to Wi-Fi, do you see the same behaviour? Are you sure your network is in reach and has the correct credentials still?

**Comment by Jeannok** [comment]
Yes the wifi is reacheable, even by your app (when I run the "test server", it connects, even if it can not complete it)

**Comment by memen45** [comment]
> As long as you are in the SubMusic menus, the phone bluetooth connection is used to connect to the internet. Only when starting the sync, the watch starts the wifi module and tries to find the network as setup in the Garmin Connect app.

The Test Server connects through your phone's Bluetooth, not through the watch wifi network!

**Comment by Jeannok** [comment]
> > As long as you are in the SubMusic menus, the phone bluetooth connection is used to connect to the internet. Only when starting the sync, the watch starts the wifi module and tries to find the network as setup in the Garmin Connect app.
> 
> The Test Server connects through your phone's Bluetooth, not through the watch wifi network!

Oki, got it. I did a "Test the network connection" in Connect App -> Forerunner 245 Music -> parameters -> Wi-fi networks . No problem detected, it just connects fine.

**Comment by chmanie** [comment]
I can attest that I have the exact same problem with the Forerunner 245 at the newest software version (I upgraded from a Venu Sq Music). Let me know if I can help debug it somehow.

**Comment by chmanie** [comment]
Okay I'm pretty sure I've figured it out. For some reason you have to sync the clock of your device with GPS before you can use WiFi sync with any music app (don't know about Spotify but definitely Deezer: https://support.garmin.com/en-US/?faq=jNABjWEeoV2WjChYTWybS6).
After I went outside (!) and let the watch figure out the GPS thing, the Sync with SubMusic also worked.

**Comment by memen45** [comment]
The Forerunner 645 had multiple reports: #18 and [#23](https://github.com/memen45/SubMusic/issues/23#issuecomment-819369632)

However, I have not been able to debug further as the wifi connection happens outside of the scope of apps. You said you notice the same behaviour for other apps as well, which further indicates it is related to the watch firmware. Please share any findings here!

You might try `Settings > Wi-Fi > Connect to Wi-Fi` on the watch and see whether that also fails.

**Comment by thekiefs** [comment]
I had this same issue pop up this morning via Plex. The watch ended up running out of battery. I fixed it by charging the watch and rebooting, but now I'm stuck on "Syncing" (perhaps a separate issue).

**Comment by memen45** [comment]
Closing this due to insufficient information. If you still have the issue, feel free to reopen!
