### ISSUE TITLE
Can't select playlists with Forunner 255s Music

### ISSUE THREAD

**Issue by lcaylat** [memen45/SubMusic#51]
Hi,

I like the principle of this application but I have a problem to recover playlists and podcasts.
Sync is working fine but I have nothing to sync 👎 
When I want to select playlists or run the server test, I get this error:
![IMG_20220731_093122](https://user-images.githubusercontent.com/65226314/182015462-b03b8974-a4f4-41bb-b45e-3a9bf5f93eea.jpg)

My Ampache server is a Debian with Nextcloud 24 and the Music module.  I tested access from Android with Power Ampache or Substreamer without issue.

I tested with Ampache API ans Submusic API.

Do you have an idea to solve this problem?
Regards.

**Comment by memen45** [comment]
Hi, thanks for your feedback! Do you have https certificates set up on your server? Some watches require proper (not self-signed) certificates or give a time out error!

**Comment by lcaylat** [comment]
I have a proper https certificate from DigiCert.

**Comment by lcaylat** [comment]
Sorry but I solve the probleme : it was the same like https://github.com/memen45/SubMusic/issues/42
My CipherSuite was too complex for Garmin Forerunner 255s but was OK with Garmin Forerunner 945. Modification in the SDK ?
I close this issue.

**Comment by memen45** [comment]
Great to hear you got it working! 
Interesting, I did not know the newer devices support those ciphers. I would expect it to be part of the SDK indeed, but apparently it is different for each device.
