### ISSUE TITLE
Some playlists won't syncronize with ampache (loop on request with action=playlist_songs)

### ISSUE THREAD

**Issue by vRoussel** [memen45/SubMusic#52]
Music server: Ampache
Device: Forerunner 245 music
App version: 0.2.2-eurotas

I have 2 playlists with 11 songs each. For the first one, the sync works correctly. For the other, it hangs indefinitely when I try to sync and never shows any progress. I checked the access.log of my reverse proxy and here's what I see. It seems like submusic is trying again and again to fetch the list of songs in the playlist.

```
192.168.1.50 - - [05/Aug/2022:18:40:37 +0200] "GET /server/json.server.php?action=playlist&filter=1&auth=BLA HTTP/1.1" 200 375 "-" "Garmin Forerunner 245 Music/10.40"
192.168.1.50 - - [05/Aug/2022:18:40:38 +0200] "GET /server/json.server.php?limit=20&action=playlist_songs&filter=1&offset=0&auth=BLA HTTP/1.1" 200 41778 "-" "Garmin Forerunner 245 Music/10.40"
192.168.1.50 - - [05/Aug/2022:18:40:38 +0200] "GET /server/json.server.php?auth=BLA&limit=20&action=playlist_songs&filter=1&offset=0 HTTP/1.1" 200 41770 "-" "Garmin Forerunner 245 Music/10.40"
192.168.1.50 - - [05/Aug/2022:18:40:39 +0200] "GET /server/json.server.php?auth=BLA&limit=20&action=playlist_songs&filter=1&offset=0 HTTP/1.1" 200 41778 "-" "Garmin Forerunner 245 Music/10.40"
192.168.1.50 - - [05/Aug/2022:18:40:39 +0200] "GET /server/json.server.php?auth=BLA&limit=20&action=playlist_songs&filter=1&offset=0 HTTP/1.1" 200 41778 "-" "Garmin Forerunner 245 Music/10.40"
192.168.1.50 - - [05/Aug/2022:18:40:40 +0200] "GET /server/json.server.php?auth=BLA&limit=20&action=playlist_songs&filter=1&offset=0 HTTP/1.1" 200 41778 "-" "Garmin Forerunner 245 Music/10.40"
192.168.1.50 - - [05/Aug/2022:18:40:41 +0200] "GET /server/json.server.php?auth=BLA&limit=20&action=playlist_songs&filter=1&offset=0 HTTP/1.1" 200 41778 "-" "Garmin Forerunner 245 Music/10.40"
...
```

I don't see anything wrong with what I get as a response from this request:
https://pastebin.com/Kmt4a0Uh

Any ideas ?

**Comment by memen45** [comment]
Interesting! Thanks for your detailed report. It might be caused by a too large response size for the playlist_songs request. Normally, SubMusic will halve the limit parameter on each try, but I see the limit is not changed. I will check the code tomorrow!

**Comment by vRoussel** [comment]
Thank you for your answer, I have no way of testing this but indeed in AmpacheProvider.mc, it seems like
```
d_params["limit"] = (d_params["limit"] / 2).toNumber();		// half the response
```

should be

```
d_limit = (d_limit / 2).toNumber();		// half the response
```

since we call the do_() function right after to retry, and that function overrides d_params["limit"]
```
d_params.put("limit", d_limit);
```

**Comment by memen45** [comment]
That is indeed the issue. Fixed it and pushed the new update to the Connect IQ store!
Thanks again for your help, let me know if the update solved your loop issue.

**Comment by vRoussel** [comment]
Alright great, thanks ! I'll check and tell you when the update appears on the store

**Comment by vRoussel** [comment]
Sorry for the delay, I had some issues with ampache itself, that I ended up solving. Anyway, your fix works great :+1:
