### ISSUE TITLE
Sync Issue: FR955 + Plex

### ISSUE THREAD

**Issue by tgiannelli-me** [memen45/SubMusic#53]
@memen45 -- I've got connectivity to the PMS (I can see playlists, and songs in playlists) when trying to sync, the watch connects to the wifi nicely, but give me an error after about 60 sec.  **GarminSdkError::0**

**Comment by memen45** [comment]
Is https working correctly? Did you try the Server Address in the browser to see if it is working?

**Comment by MattGraz** [comment]
@memen45 - Can you elaborate what you mean by the "Server Adress in the browser".  I'm assuming you don't mean `app.plex.tv`.

**Comment by memen45** [comment]
Custom ports are not supported by the Garmin watch software. See also the discussion memen45/submusic#33

You could change Plex settings to port 443, then enable https (I don't have Plex server installed, so I am not sure about the exact steps).
Or you could leave the Plex settings as is, and set up a Proxy server in e.g. Apache. It is definitely possible to set up https against an Apache proxy server, this is also explained in #33.

Hope this helps, in case you still have issues, please contact me directly (contact developer through Garmin connect app) or open a new issue as to not clutter this one!

**Comment by MattGraz** [comment]
Thank you for the details, much appreciated.

**Comment by tgiannelli-me** [comment]
@memen45  -- have made some progress here... I have the plex public IP coming in via port 443 over https.  I connect to the plex server and can see the playlist I want to sync.  

when trying to sync now, I get the GarminSdkError::0

I have setup a reverse proxy on my NAS going from :443 to :32400 
I have my Router setup to forward :443 traffic to :32400
File formats are all MP3

what might I be missing?

**Comment by memen45** [comment]
Do you have valid HTTPS certificates installed? And do you have sufficient TLS ciphers enabled (see #42)?

**Comment by tgiannelli-me** [comment]
I’ve been using the veers issues by synology. However I’ll investigate a different CA. Let’s encrypt is mentioned a lot here I’ll see if I can’t get that working and will have a look at the other issue.

Thanks!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by memen45** [comment]
Any updates or can it be closed?

**Comment by tgiannelli-me** [comment]
Closed – not using the app anymore

Tom Giannelli
***@***.******@***.***>
604.349.6463
