### ISSUE TITLE
400 INVALID_HTTP_... error when trying to connect

### ISSUE THREAD

**Issue by chmanie** [memen45/SubMusic#55]
Hi! Thank you so much for building this, I really appreciate all your work done here.

However I have a problem to connect to my server (I tried navidrome subsonic and nextcloud ampache). On both I get the following error on my watch:

```
GarminSdkError:-
400
Error HTTP ->
GarminSdkError:
INVALID_HTTP_,,,
```

it stops there, so I can't really tell what the issue is exactly. Is there a way to debug this more? Thanks again!

**Comment by chmanie** [comment]
I tried setting up a fresh ampache server with version 5.4.1 and I'm getting a similar (albeit not the exact same) error:

```
ApiError::BADRESPONSE Error API --> ApiError::BADRESPONSE
```

I tried using the app `Amperfy` and it doesn't seem to have any problem with the server. Sorry, I'm really clueless here :(

**Comment by memen45** [comment]
The first error is most likely related to incorrect url. For Nextcloud make sure you use:
`https://domain.com/apps/music/subsonic` or
`https://domain.com/apps/music/ampache`
And of course, the owncloud/music app should be installed.

For Ampache server, try using the latest version, 5.5+, as there was a small issue with earlier versions.

**Comment by chmanie** [comment]
Hey, thanks so much for getting back to me. I installed the latest version of ampache (5.5.1) and it's sadly still the same error. When I press "Show server settings" it is properly recognized:
```
[SERVER URL]
[USERNAME]
Ampache API
Version: 5.5.1
```
but doing a "Server test" or fetching the playlists still result in the issue described above (second post).

**Comment by memen45** [comment]
Thanks for your feedback. Are you able to log the content of the responses? That way I could check whether the response is indeed malformed or not. 

Another option is to create a temporary account on Ampache server on which I can test the responses in the debugger. You can send it through the 'Contact Developer' option in the Connect IQ store page.

**Comment by chmanie** [comment]
I'm sorry I can't reproduce it anymore as I switched to Nextcloud again. Version 24 of nextcloud and the Music Plugin v1.6 do not seem to have the above error! Thank you for helping in any case!
