### ISSUE TITLE
Add Plex transcoding

### ISSUE THREAD

**Issue by memen45** [memen45/SubMusic#56]
1. I found some documentation [here](https://forums.plex.tv/t/music-transcoding-api/696895) on using transcoding for music in the Plex API. I think this should work?

_Originally posted by @thekiefs in https://github.com/memen45/SubMusic/issues/33#issuecomment-1236183917_

**Comment by exonight** [comment]
I'm successfully transcoding files from FLAC to MP3 with the minimum following html:
https://MASKED.plex.direct:32400/audio/:/transcode/universal/start.m3u8?X-Plex-Platform=Chrome&path=/library/metadata/10249&X-Plex-Token=MASKED

I do believe the MP3 files are wrapped and streamed over m3u8 which Garmin also supports but may break something come implementation.

A more proper verson of the request (makes the logs happier) might be something roughly like this:
https://MASKED.plex.direct:32400/audio/:/transcode/universal/start.m3u8?X-Plex-Platform=Chrome&copyts=1&mediaIndex=0&offset=0&path=/library/metadata/10249&X-Plex-Token=MASKED&X-Plex-Platform-Version=OSverNum&X-Plex-Client-Platform=GarminOS&X-Plex-Client-Identifier=WatchSerialNumber&X-Plex-Device=GarminWatchName&X-Plex-Product=SubMusic&X-Plex-Username=plexuser&X-Plex-Device-Name=GarminWatch&X-Plex-Version=1.0

**Comment by memen45** [comment]
Does it work always and by default? Or are there situations/settings that could disable transcoding?

If it works, SubMusic could request transcoded by default. Currently the media url is stored from the first available file. This could be changed to the `/library/metadata/:id` path instead. 

@exonight what format does your request return? In the link above a different endpoint is used (`/music/` instead of `/audio/`) and the 'add-transcode-target' defines the audio codec. This could be set to mp3 always. In your example however, there is no codec defined, so as I understand the m3u format, the files will still have their original codec?

**Comment by exonight** [comment]
I am not an expert, but I believe since transcoding is a core feature of plex it should work reliably.
Platform=Chrome is the most important piece of information there, that's one of plexes built in codec definitions. 
@thekiefs example tries to define a custom platform, but I messed around with it for a number of hours with no success; I'm sure it possible though, and would no doubt give you greater control.

 I would personally recommend transcoding only for formats that don't match garmin's list.  Transcoding takes time and CPU resources that can be avoided if the media is already in the correct format,  Additionally it avoids the wrapper format needed to stream the media instead of just downloading a file.

**Comment by exonight** [comment]
My format streams an mp3 format wrapped in an m3u8 file. I was able to wget that URL and save it as an mp3 file with no problem in my testing. Just note it's not a cut-and-dry download, at least some file manipulation is needed, even if minimal.

**Comment by memen45** [comment]
Thanks for testing! Most important thing is that the `Content-Type` response headers are correct. Garmin watch software will reject if those headers do not match the requested encoding format. If requesting for example ENCODING_MP3, the response should have `Content-Type: audio/mpeg`. Otherwise the response will not be loaded.

I will check with a test instance of Plex when I have time!

**Comment by memen45** [comment]
After a lot of trial and error, I finally could obtain the mp3 file. I went with the solution referenced in the first post, as it is possible to explicitly state the codec as mp3. The transcoding should work in the latest release 0.2.4-amyklas. 

If you have any issues, feel free to reopen or start a new issue.
