### ISSUE TITLE
40 minute limit for playlist sync

### ISSUE THREAD

**Issue by memen45** [memen45/SubMusic#59]
I just noticed that there seems to be a 40 minute limit for playlist sync.  I had a playlist of 65 minutes, only synced 40 minutes,  Another playlist of 75 minutes - synced only 40 minutes.  Not a big issue and I can work around it, but just wanted to make sure you were aware of it.

_Originally posted by @cvernon0 in https://github.com/memen45/SubMusic/issues/58#issuecomment-1282471357_

**Comment by memen45** [comment]
Have you tried do resync? It might be the sync is timed out by the watch due to the long downloads.
Does the playlist show a 'needs sync' comment?

**Comment by memen45** [comment]
I found the issue, the 'number to be received' was stuck on 1, so for paged API access only the first page was retrieved. Fixed it now to 10000, as intended. See version 0.2.6 in the Connect IQ store.

**Comment by cvernon0** [comment]
It's working great now, thanks again!
________________________________
