### ISSUE TITLE
GarminSdkError:0

### ISSUE THREAD

**Issue by mkriegl** [memen45/SubMusic#60]
Yesterday I got a Garmin Fenix 7X and also found your interesting tool Submusic with Nextcloud Support. 
I did the setup as described and added one song for testing purposes to one playlist. 
Test Server stops with no Podcasts found. 
I do see the one playlist that I set up, but when I start synchronizing I get an GarminSdkError:0
Any Ideas how to fix this?

**Comment by memen45** [comment]
First thought: HTTPS/SSL problem or you used a custom port in the url e.g. `domain.com:<port>`.

**Comment by mkriegl** [comment]
I am using 2VMs on the same machine. One reverse proxy and one for nextcloud. 
Entry point for my nextcloud is a subdomain xxx.myserver.com with https on 443 and letsencrypt using nginx. 
Proxy_pass is via https network internally via IP 192.168.xxx.xxx - does this might make an issue?
Nextcloud is working as expected

Only thing I recognized on my nextcloud VM nginx configuration is following commented out:
#    location ~ \.(?:flv|mp4|mov|m4a)$ {
#       mp4;
#       mp4_buffer_size 100M;
#       mp4_max_buffer_size 1024M;
#       fastcgi_split_path_info ^(.+?.php)(\/.*|)$;
#       set $path_info $fastcgi_path_info;
#       try_files $fastcgi_script_name =404;
#       include fastcgi_params;
#       include php_optimization.conf;
 #   }

I guess I commented this out in the past as when added, nginx does not start anymore

**Comment by memen45** [comment]
It is difficult to say on custom server configs, but if everything is working while using the nextcloud music app from the browser, it generally should also work from SubMusic.

If you can make a temporary account, and send it through the 'Contact developer' option, I might be able to see what is going wrong in more detail.

**Comment by mkriegl** [comment]
Did you receive the details via e-mail? Could you already have a look on it?

**Comment by memen45** [comment]
Did not receive anything yet! Did you send it through [here](https://apps.garmin.com/en-US/apps/600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794/contactdeveloper)?

**Comment by mkriegl** [comment]
Ah, on Garmin :-) .. I was looking on github and just found an e-mail address I used. I forwarded the content through the garmin developer portal

**Comment by memen45** [comment]
Was able to fix my development env. Tested against your server and found no issues at all. Only thing that I can think of is SSL cipher issues as described in #42. Potential fix is there as well, so hopefully that helps! Let me know if you were able to solve it.

**Comment by memen45** [comment]
Closing since there are several new versions since the issue. If you still have the problem, feel free to reopen!

**Comment by mkriegl** [comment]
I did not do any changes, but Sync it is working right now. Thank you .. max
