### ISSUE TITLE
GarminSdkError::-400

### ISSUE THREAD

**Issue by Fl0r14n** [memen45/SubMusic#63]
GarminSdkError::INVALID_HTTP_BODY_IN_NETWORK_RESPONSE

This is what I get when getting up the playlist or testing the server with plex api.
The weird thing is, that when I go to server to see the settings, it shows my configured setting and resolves the plex server version

The way I configured it is 
https://[ip].[hash].plex.direct:32400
plex username
and X-Plex-Token

This is the best I could get to. All other options give 300 (different domain with port fwd with http or https)
The watch is epix2 sw ver 10.44B

**Comment by memen45** [comment]
An immediate -300 timeout error most likely indicates an https certificate or ssl cipher issue.
What version of the plex server are you using? Were you able to test endpoints directly on your ip address?

**Comment by Fl0r14n** [comment]
Plex version: 1.29.2.6364 from about in plex and 1.29.2.6364-6d72b0cf6 on the watch

"Were you able to test endpoints directly on your ip address?": If I paste in the browser 
https://[ip].[hash].plex.direct:[port]/playlists?X-Plex-Token=[token] 
then I can see a xml media container with a list o playlist objects.
If I do "select playlists" on the watch it will give me the 400 invalid http body in network response

If the settings are wrong for example in the "Server" entry on the watch, I will see just my settings without version and a 300 after a while. If they are ok, plex server version appears almost instantly.

300 seems to appear if the url is wrong (I guess it should be a 404) and also if using http or self signed https certificate. (tried port fwd with ddns.net on the router for both). I did not set a reverse proxy, because I will still have the self signed certificate issue. Also, kinda makes no sense, since plex direct url works and the watch displays the plex server version. So something is working

**Comment by Fl0r14n** [comment]
Found it! The token was wrong. For some reason it appended the token + the default value which was "key"

The plex version displayed by the watch matches the MediaContainer version attribute in the /identity endpoint, but the identity endpoint is public that's why it was working

**Comment by memen45** [comment]
Yes, indeed `/identity` is requested without authentication. That should have given it away. Glad you found the cause. Hope you enjoy SubMusic!
