### ISSUE TITLE
SubsonicAPI BADRESPONSE Error

### ISSUE THREAD

**Issue by MochaMage** [memen45/SubMusic#7]
Hi, I have tried setting up my Garmin Vivoactive 3 Music with the Subsonic API but when I try to sync with my Airsonic server, I get the error from the subject line. I am using Garmin Express on Windows to configure Submusic and have verified that I am using the same server address  and credentials that I use in the Subsonic Android application. I have noticed that the configuration screen has an API Key field instead of a password field so I'm not sure if that is the cause of the issue, since the README states that I should be using my password when using the Subsonic API.

**Comment by MochaMage** [comment]
Going through the catalina log shows the following error as being the cause

`[2020-11-24 10:51:27] [info] 2020-11-24 10:51:27.293 ERROR --- o.s.b.w.support.ErrorPageFilter          : Forwarding to error page from request [/rest/getPlaylists] due to exception [The request was rejected because the URL was not normalized.]
[2020-11-24 10:51:27] [info] org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.`

**Comment by MochaMage** [comment]
Found the cause, Spring did not like the / at the end of the URL I was putting

**Comment by memen45** [comment]
The URL should indeed end without a trailing slash. Good to see that you were able to solve the issue.
