### ISSUE TITLE
PLEX - Media Error Occured

### ISSUE THREAD

**Issue by paulshemrock** [memen45/SubMusic#70]
Hello,

first of all - thanks for this awesome app! Will save me hours of picking mp3 files just for my running watch.

When syncing with PLEX there is a first round where it syncs from 0 to 100%. It then goes back to 0% and interrupts with an error message "Media Error Occurred" and the App closes. 
Both Plex and Garmin (FR255) are running on the latest version.

I can see all playlists. 
Server test returns "Inlog OK" and then returns SDK error 403 http "Network response out of memory". Same if I want to show songs of a playlist.

Any idea why I get this and what I can do about it? 
For one playlist it worked, but now I am stuck at this stage.

Thanks 
Paul

**Comment by memen45** [comment]
For future reference, this was handled through email. Lowering the number of playlists/songs on playlists is the only workaround.
