### ISSUE TITLE
Using Back button leads to "media error" 

### ISSUE THREAD

**Issue by qudiqudi** [memen45/SubMusic#72]
There seems to be a bug when navigating through the SubMusic's menu on my Forerunner 945 LTE.
Using the back-button on the watch (button at the 4 o'clock position) when going back to a parent item in the menu, the app force closes with "media error" and I have to start from the home watch face. This makes navigating the SubMusic's menu on the watch really tedious.

Example:

- open SubMusic through the media player settings.
- selecting menu item "Podcasts"
- chose a Podcast from the list
- using the back button to go back to the list of podcasts
- "media error" -> back to watch face
- start over...

SubMusic version 0.2.8-oebalus
Forerunner 945 LTE SW version 14.52 [DFU-9753aa]
Garmin Connect version 4.64
Garmin Connect IQ version 2.20

**Comment by memen45** [comment]
May be caused by Out of Memory error, but I am not sure. Will check when home in a couple of days.

**Comment by memen45** [comment]
Your device seems to be the only one affected. As far as I can see, there should be no reason for the Error to occur. Did you update your watch to the latest software version? Do you get this error more often or only in specific menus?
Otherwise we would have to open a bug ticket on the Garmin Developer forum.

**Comment by qudiqudi** [comment]
AFAICT it's the latest sw for the Forerunner 945 LTE. It happens every time I use the back-functionality inside SubMusic. From Playlists back to the main menu, or from "more", or from Podcast, doesn't matter. Going back to a parent menu gives the "media error". It there any way to debug this, debug report export? Using "test server" works, as well as the rest of the app, it just navigation makes it hard to use - or say - more time consuming ...

**Comment by memen45** [comment]
Ah okay. I do not think debugging further will help in this case. I see the error in the logs at exactly this line of code:
https://github.com/memen45/SubMusic/blob/1f3fba228966959d503b004ee0220291695d0c67/source/View/SubMusicMenu.mc#L231
This is a function call to the Garmin SDK, and the crash only occurs on your device. I am not sure why, so best option is to open a ticket directly with Garmin. [See here](https://forums.garmin.com/developer/connect-iq/i/bug-reports/onback---symbol-not-found-on-forerunner-945-lte)

**Comment by qudiqudi** [comment]
Alright, thanks for looking into to it. Interestingly, the back functionality works in the Spotify app.

**Comment by mathsaey** [comment]
For the record, I have the exact same issue with the "Podcasts" app (the back button causes a "Media Error Occurred" crash). Also running 14.52 on a 945LTE. Pretty sure Garmin is to blame for this.

**Comment by memen45** [comment]
Is this still relevant or is the issue fixed by Garmin in the meantime?

**Comment by qudiqudi** [comment]
Unfortunately, yes. Nothing changed so far, with the last update. I'm sure Garmin just doesn't care about that issue.

**Comment by memen45** [comment]
Thanks for sharing! I have pinged the Garmin issue. It has the 'Acknowledged' state, but they are not the fastest with fixing bugs indeed. Hope it does not take too long.

**Comment by qudiqudi** [comment]
This "menu navigation" error seems to be fixed. Now I have a new one, will open an issue.
