### ISSUE TITLE
Navidrome server

### ISSUE THREAD

**Issue by wmmak12** [memen45/SubMusic#73]
Can I still connect to submusic if I only have a navidrome server? What do I input for the api key?

**Comment by memen45** [comment]
Yes you can! Will update the docs, but navidrome adheres to the subsonic API, so you can follow the guide for setting up Subsonic. API key field is your password. Hope this helps!

**Comment by memen45** [comment]
It means the connection to your phone is not working properly. Make sure all is synced between your phone and watch. Also sometimes a reboot of either or both is needed.
