### ISSUE TITLE
Forerunner 945. Ampache.  Failed invoking <symbol>

### ISSUE THREAD

**Issue by slytekorg** [memen45/SubMusic#78]
Hey. Sometimes it sync, but most of attempts it doesn't work. Always have error with sync, server test, server settings etc.

```
Error: Unexpected Type Error
Details: 'Failed invoking <symbol>'
Time: 2023-08-21T11:42:44Z
Part-Number: 006-B3113-00
Firmware-Version: '13.00'
Language-Code: eng
ConnectIQ-Version: 4.2.2
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 77
Filename: D8KG0616
Appname: SubMusic
Stack: 
  - pc: 0x1000cc0d
  - pc: 0x1000cb6e
  - pc: 0x1000dac6
  - pc: 0x1000da69
  - pc: 0x1000b4a0
  - pc: 0x1000b5ee
  - pc: 0x10004028
```

**Comment by memen45** [comment]
Hi,

Thanks a lot for your feedback. I received at least one similar report this week. Unfortunately, it seems like even the Garmin dev environment is not working. I cannot check the crash reporting at all, so I have no idea how to address issues for now. :(
