### ISSUE TITLE
getting error -400

### ISSUE THREAD

**Issue by sae87** [memen45/SubMusic#79]
Hi there, i've tried to follow the instructions that have been provided, but when testing server, i get the error on my FR745

GarminSdkError:: -400
Error HTTP -->
GarminSdkError::INVALID_HTTP_BODY_IN_NETWORK_RESPONSE. 

server address: https://192-168-86-XX.0ae2ba71cfaXXXXXXXXXXXXXXXXXXXX.plex.direct:32400/
API key: the thing that appears after the Plex-Token=XXXXXX 

version: 0.2.10-hippocoon 
running a plex server

i've pulled out the right required server address and token, played around with the auth method to no avail, and have not seen anyone getting the same error number as myself.

Do tell me if you need other details.

would appreciate any help that i can get. thank you!

**Comment by memen45** [comment]
Thanks for opening this issue. Could you try and remove the trailing slash from the Server Adress in settings?

You could also try and open your browser, fill in the <url>/identity and check if you get a response. On a blank page right-click > view source. If you get either an xml or JSON document, your url should be okay.

**Comment by DanShrader** [comment]
I was having the same error and removing the trailing slash made it work as expected.  Thanks
