### ISSUE TITLE
Sync finishes but no downloaded podcast episodes appear

### ISSUE THREAD

**Issue by qudiqudi** [memen45/SubMusic#80]
Test is successful, so is a sync if I tagged a podcast with "make newest episode available". If I sync,  it appears to download something - takes a little bit of time - but it is way too fast for a whole podcast and no episodes appear under "Episodes", it says "Nothing to show".
Playlists work fine though, Songs download and can be played.

I tried to empty device storage via the settings menu, but that didn't do it.

SubMusic version 0.2.10-hippocoon
Forerunner 945 LTE SW version 15.19
Garmin Connect version 4.70
Garmin Connect IQ version 2.23

**Comment by moguls753** [comment]
I can confirm this, the exact same problem occurs for me. Playlist sync is succesfull, Even though under More... - Browse - Podcasts it says "Local - synced" to each one.

SubMusic version 0.2.10-hippocoon
Forerunner 265s version 4.19
Garmin Connect IQ version 2.23.1

**Comment by memen45** [comment]
What servers/backends are you using? Could it be related to the large file size? Or missing support server side? Many possibilities here!

**Comment by qudiqudi** [comment]
Backend is nextcloud 27.1.0 and music app 1.8.4 with the ampache api Version: 44
File size doesn't mater, I tested it with big music files added to a playlist. Submusic downloads them just fine. <1 GB.
Compared to single podcast episodes with rougly 400 MB that just not get downloaded.

**Comment by memen45** [comment]
Can you elaborate on the following:

- in SubMusic, Menu > Podcasts (and if there is any, tap and choose Episodes)
- in SubMusic, Menu > More > Browse > Podcasts

Does it show the same?

If you check the podcast, does it have mp3 files available? Cause the watch has only limited number of file formats available, and it will skip downloads that have different file formats.

**Comment by qudiqudi** [comment]
`in SubMusic, Menu > Podcasts (and if there is any, tap and choose Episodes)`

It says "nothing to show" for each podcast.

`in SubMusic, Menu > More > Browse > Podcasts`

It shows every Podcast I subscribed to in nextclouds music app.

`in SubMusic, Menu > More > Browse > Podcasts`

I just checked for each podcast, except one that is of _MIME-Typ audio/mp4_, all are mp3.
I want to add, that I'm using Submusic for years now, it used to work with the same hardware, watch and nextcloud server, so I'm inclined to suspect a software bug.
Let me know if you need further details.

**Comment by memen45** [comment]
Can you check Menu > Settings > Storage and see if you have sufficient Memory (metadata is stored here) and Media Cache (songs and podcasts audio files will go here) available to make the download?

**Comment by qudiqudi** [comment]
I actually tried it with "Remove data" multiple times.
Just did and it now sits at,
Memory: 175 Kb/507Kb
Media: 64 Kb/1.8 Gb

Trying to sync after that does nothing, unfortunately.

**Comment by memen45** [comment]
Did you try
- reboot of the watch
- reinstall of SubMusic

That should reinitialize the memory completely and hopefully solve the issue. Out of memory errors are not actively handled yet in SubMusic, so if either memory or media cache is filled, you might not notice it and it might corrupt the memory. Especially a fail to write metadata leaves media files in storage forever, limiting your total storage in the future, until you remove the app data.

**Comment by qudiqudi** [comment]
Just did a reboot and a reinstall. Still the same behavior, playlists download fine, podcasts don't.

**Comment by memen45** [comment]
So, no progress yet, unfortunately.

Are you able to get any logs from the watch and server?

On the watch you can create a log by:
- connect the watch to a PC with USB and pre-create a file in \garmin\apps\logs named SUBMUSIC.txt
- open the SubMusic Menu > Settings > App Settings > Enable Debugging (Log debug info to file).

Then, navigate to the Sync and run it. Afterwards, disable the debugging and move the file from the watch (leaving it enabled slows down the app).

You can either send it to me through the 'Contact Developer' option in the Garmin connect IQ app store, or make sure to remove any sensitive data before posting here!

Server logs could be helpful as well!

**Comment by qudiqudi** [comment]
So after getting through the hurdle to get access to the Garmin storage on a Mac, I observed an interesting behavior: 
If I activate the debug logging I get "media error" on a sync and the app crashes, deactivating debug logging with it. I can repeat theses steps but to no better outcome. I suspect it's a file ownership thing, but can't be sure. Would be better if the app could natively create log files, which one than can extract.
  
As for the server log files, nothing regarding the music app. Connection with the server works just fine, as I said, playlist download flawlessly.

**Comment by memen45** [comment]
Thanks for your feedback! Actually, this provides some information to me. The Media Error shows up in the crash logs, so I found it is caused by some http error. This could indicate the source of the problem, as downloads will be silently skipped on any error.

Could you obtain access logs of the server during a sync? This should give a list with all requests that are coming in, and the HTTP response codes with it.

**Comment by memen45** [comment]
By the way, I think that despite the media error, there should be log contents in the log file. These could be very helpful, as the last request and response will be in there in detail! Could you share these through the 'Contact developer' option [here](https://apps.garmin.com/en-US/apps/600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794)? Or please sanitize it first before posting in this thread. Thanks in advance!

**Comment by moguls753** [comment]
I can provide my nextcloud logfile. This one is the sucessfull playlist sync:
``` bash
172.16.0.238 - - [26/Sep/2023:09:00:20 +0000] "GET /apps/music/ampache/server/json.server.php?auth=e182cf02c93700f2b9cb6dc86015965683c107be4355596c6f70e75469e0f996&timestamp=1695718814&action=handshake&user=eike&version=440000 HTTP/1.1" 200 1884 "-" "Garmin Forerunner 265S/16.17"
172.16.0.238 - - [26/Sep/2023:09:00:20 +0000] "GET /apps/music/ampache/server/json.server.php?action=playlist&filter=3&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 200 1874 "-" "Garmin Forerunner 265S/16.17"
172.16.0.238 - - [26/Sep/2023:09:00:20 +0000] "GET /apps/music/ampache/server/json.server.php?limit=20&action=playlist_songs&filter=3&offset=0&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 200 2043 "-" "Garmin Forerunner 265S/16.17"
172.16.0.238 - - [26/Sep/2023:09:00:26 +0000] "GET /apps/music/ampache/server/json.server.php?action=get_art&id=21&type=song&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 404 1693 "-" "Java/11.0.19"
```

And this one is the podcast sync:
``` bash
172.16.0.238 - - [26/Sep/2023:09:02:13 +0000] "GET /apps/music/ampache/server/json.server.php?action=playlist&filter=3&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 200 1871 "-" "Garmin Forerunner 265S/16.17"
172.16.0.238 - - [26/Sep/2023:09:02:13 +0000] "GET /apps/music/ampache/server/json.server.php?limit=20&action=playlist_songs&filter=3&offset=0&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 200 2043 "-" "Garmin Forerunner 265S/16.17"
172.16.0.238 - - [26/Sep/2023:09:02:13 +0000] "GET /apps/music/ampache/server/json.server.php?action=podcast&filter=5&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 200 1969 "-" "Garmin Forerunner 265S/16.17"
172.16.0.238 - - [26/Sep/2023:09:02:13 +0000] "GET /apps/music/ampache/server/json.server.php?limit=5&action=podcast_episodes&filter=5&offset=0&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 200 3274 "-" "Garmin Forerunner 265S/16.17"
172.16.0.238 - - [26/Sep/2023:09:02:13 +0000] "GET /apps/music/ampache/server/json.server.php?action=stream&id=1779&type=podcast_episode&format=raw&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 303 1758 "-" "Garmin Forerunner 265S/16.17"
172.16.0.238 - - [26/Sep/2023:09:02:20 +0000] "GET /apps/music/ampache/server/json.server.php?action=get_art&id=21&type=song&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 404 1689 "-" "Java/11.0.20"
172.16.0.238 - - [26/Sep/2023:09:02:21 +0000] "GET /apps/music/ampache/server/json.server.php?action=get_art&id=5&type=podcast&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 200 17621 "-" "Java/11.0.19"
172.16.0.238 - - [26/Sep/2023:09:02:21 +0000] "GET /apps/music/ampache/server/json.server.php?action=get_art&id=5&type=podcast&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 200 17619 "-" "Java/11.0.19"
```
The SUBMUSIC.txt on the Watch stays empty, but there is a CIQ_LOG.YML:
``` yml
---
Error: Unexpected Type Error
Details: 'Failed invoking <symbol>'
Time: 2023-09-26T08:27:02Z
Part-Number: 006-B4258-00
Firmware-Version: '16.17'
Language-Code: deu
ConnectIQ-Version: 4.2.2
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 77
Filename: D93I1027
Appname: SubMusic
Stack: 
  - pc: 0x1000cc0d
  - pc: 0x1000cb6e
  - pc: 0x1000d865
  - pc: 0x1000d79b
  - pc: 0x1000b47f
  - pc: 0x1000b669
  - pc: 0x1000397a
---
Error: Unexpected Type Error
Details: 'Failed invoking <symbol>'
Time: 2023-09-26T08:28:09Z
Part-Number: 006-B4258-00
Firmware-Version: '16.17'
Language-Code: deu
ConnectIQ-Version: 4.2.2
Store-Id: 600bd75f-6ccf-4ca5-bc7a-0a4fcfdcf794
Store-Version: 77
Filename: D93I1027
Appname: SubMusic
Stack: 
  - pc: 0x1000cc0d
  - pc: 0x1000cb6e
  - pc: 0x1000d865
  - pc: 0x1000d79b
  - pc: 0x1000b47f
  - pc: 0x1000b669
  - pc: 0x1000397a%       
```

**Comment by moguls753** [comment]
I just noticed that there was no file synchronization in my first log file. here's one:
```bash
172.16.0.238 - - [26/Sep/2023:09:25:49 +0000] "GET /apps/music/ampache/server/json.server.php?offset=0&auth=2ad5601a91c2e9ca81714cb9c93a976d&limit=20&action=playlists HTTP/1.1" 200 1896 "-" "Mozilla/5.0 ( compatible )"
172.16.0.238 - - [26/Sep/2023:09:25:59 +0000] "GET /apps/music/ampache/server/json.server.php?action=playlist&filter=3&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 200 1875 "-" "Garmin Forerunner 265S/16.17"
172.16.0.238 - - [26/Sep/2023:09:26:00 +0000] "GET /apps/music/ampache/server/json.server.php?limit=20&action=playlist_songs&filter=3&offset=0&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 200 2250 "-" "Garmin Forerunner 265S/16.17"
172.16.0.238 - - [26/Sep/2023:09:26:00 +0000] "GET /apps/music/ampache/server/json.server.php?action=podcast&filter=5&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 200 1967 "-" "Garmin Forerunner 265S/16.17"
172.16.0.238 - - [26/Sep/2023:09:26:00 +0000] "GET /apps/music/ampache/server/json.server.php?limit=5&action=podcast_episodes&filter=5&offset=0&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 200 3274 "-" "Garmin Forerunner 265S/16.17"
172.16.0.238 - - [26/Sep/2023:09:26:01 +0000] "GET /apps/music/ampache/server/json.server.php?action=stream&id=22&type=song&format=raw&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 200 1556673 "-" "Garmin Forerunner 265S/16.17"
172.16.0.238 - - [26/Sep/2023:09:26:03 +0000] "GET /apps/music/ampache/server/json.server.php?action=stream&id=24&type=song&format=raw&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 200 2705745 "-" "Garmin Forerunner 265S/16.17"
172.16.0.238 - - [26/Sep/2023:09:26:07 +0000] "GET /apps/music/ampache/server/json.server.php?action=stream&id=25&type=song&format=raw&auth=2ad5601a91c2e9ca81714cb9c93a976d HTTP/1.1" 200 2459906 "-" "Garmin Forerunner 265S/16.17"
```

**Comment by memen45** [comment]
Thanks for the logs! I see there is a 303 redirect when the download is requested for the podcast episode. That is most likely the cause of the issue. The HTTP 303 is not handled (and also causes the Media Error when logging is enabled) and the download is silently cancelled.

The relevant code in the owncloud/music app is [here](https://github.com/owncloud/music/blob/3b1db7a849fa0feac12bf144b4af8402936ce79d/lib/Controller/AmpacheController.php#L865). I am running the same app version 1.8.4, but I somehow do receive HTTP 200 responses instead of HTTP 303.

Solution to support this in SubMusic:
- extract the redirect url from the 303 response and follow it (also check other HTTP redirect codes?). If I understand correctly, there should be a 'Location' header in the response, which contains the updated url: [here](https://github.com/nextcloud/server/blob/f18e73137c6112ac81b151c0670333aec88bf2ed/lib/public/AppFramework/Http/RedirectResponse.php#L52C20-L52C44)

**Comment by moguls753** [comment]
> I see there is a 303 redirect when the download is requested for the podcast episode. 

But isn't that logical? The episodes aren't stored on the nextcloud server; they're streamed. So, the server redirects to the streaming URL of the podcast episode. Or am I missing something?

**Comment by memen45** [comment]
The server could act as a proxy as well, or even predownload episodes and then directly serve from cache. Ampache server returns 200 as well. 

But indeed, using a redirect makes sense as well and reduces unnecessary load on the nextcloud server.

**Comment by memen45** [comment]
> * extract the redirect url from the 303 response and follow it (also check other HTTP redirect codes?). If I understand correctly, there should be a 'Location' header in the response, which contains the updated url: [here](https://github.com/nextcloud/server/blob/f18e73137c6112ac81b151c0670333aec88bf2ed/lib/public/AppFramework/Http/RedirectResponse.php#L52C20-L52C44)

This seems to be not possible. There is no access to headers in the response on the watch. I need a confirmation that this 303 is indeed not followed by the watch. Only then I can open a bug ticket with Garmin and see what the watch behaviour should be. 

Unfortunately, I am still not able to test the Sync process in the simulator, and therefore hesitant to release the following update. The update should fix the Media Error when logging is enabled, and some other fixes as well. Will update.

**Comment by memen45** [comment]
Just verified with my Nextcloud server. I actually do get 303, 307 and a 302 in sequence. Tested on a Vivoactive 4S and it works without issue.

**Comment by moguls753** [comment]
I tested the URL below in my browser and was redirected to the appropriate URL with a 303 status code. Subsequently, I successfully downloaded the podcast episode without any issues.

`nextcloud.mydomain.com/apps/music/ampache/server/json.server.php?action=stream&id=1779&type=podcast_episode&format=raw&auth=...`

Given that the 'location' key in the response header is accurate, if it functions on your Vivoactive 4S, then the issue shouldn't be related to the redirect, right?

**Comment by qudiqudi** [comment]
> I tested the URL below in my browser

Just tested this too, I see the exact behavior. Browser follows the redirect and downloads the episode.
My log looks like that when syncing Submusic:

```
"GET /apps/music/ampache/server/json.server.php?action=podcast&filter=3&auth=... HTTP/1.1" 200 
"GET /apps/music/ampache/server/json.server.php?limit=5&action=podcast_episodes&filter=3&offset=0&auth=... HTTP/1.1" 200 
"GET /apps/music/ampache/server/json.server.php?action=podcast&filter=8&auth=... HTTP/1.1" 200 
"GET /apps/music/ampache/server/json.server.php?limit=5&action=podcast_episodes&filter=8&offset=0&auth=... HTTP/1.1" 200
"GET /apps/music/ampache/server/json.server.php?action=stream&id=2027&type=podcast_episode&format=raw&auth=... HTTP/1.1" 303 
"GET /apps/music/ampache/server/json.server.php?action=stream&id=2022&type=podcast_episode&format=raw&auth=... HTTP/1.1" 303 
```

**Comment by qudiqudi** [comment]
This has been fixed my either Garmin Update or Submusic update. Thanks!

**Comment by memen45** [comment]
Thanks for the update! Hope you enjoy using SubMusic!
