### ISSUE TITLE
Sync with Plex

### ISSUE THREAD

**Issue by augoric** [memen45/SubMusic#81]
Hi there,  I'm having a really hard time trying to sync my music with plex.  I've followed the instructions and have my hashcode and token.

when i enter the address like in the instructions (replace [IP-Address], [Hash], [Token] with actual values), it says no playlists available
https://[IP-Address].[Hash].plex.direct:32400/
test - error 400

if i do something like this found on the plex instructions, it give me this result
https://[IP-Address].[Hash].plex.direct:32400/?X-Plex-Token=[Token]
test - inlog ok, but no playlists

if i do this, i get the same result as above
https://[IP-Address].[Hash].plex.direct:32400/library/sections/1?X-Plex-Token=[Token]
test - inlog ok, but no playlists

this is the closest i've gotten,  i can find the playlists, but they are not syncing
https://[IP-Address].[Hash].plex.direct:32400/playlists/?X-Plex-Token=[Token]
test - inlog ok

i'm sure there is something not quite right with my server address, but i just can't figure out what it is

**Comment by memen45** [comment]
Thanks for your feedback! Did you enter the token as the password? And what device are you using?

**Comment by augoric** [comment]
When you say password,  I'm assuming you mean api key, if so yes. I have the token entered. 

My device is garmin forerunner 745

**Comment by memen45** [comment]
https://github.com/memen45/SubMusic/issues/79

Seems related! Could you check the server address in the browser as well?

**Comment by augoric** [comment]
Yes it works in a browser. this is my browser output using this server address
https://[IP-Address].[Hash].plex.direct:32400/playlists/?X-Plex-Token=[Token]

what should my server address look like? am i entering it correctly?

**Comment by memen45** [comment]
It should be as you showed in your first example, and as it is shown in the readme. I notice, however, there should not be a trailing slash. So instead of
`https://[IP-Address].[Hash].plex.direct:32400/` could you try `https://[IP-Address].[Hash].plex.direct:32400`?

**Comment by augoric** [comment]
OMG!!! its working!!!

that did it, just had to remove the /.  thank you so much :)

**Comment by memen45** [comment]
Thanks for your feedback! Will update the docs.
