### ISSUE TITLE
Plex GarminSdkError::-400

### ISSUE THREAD

**Issue by lucasartori** [memen45/SubMusic#85]
GarminSdkError::-400 INVALID_HTTP_BODY_IN_NETWORK_RESPONSE

I get this error testing the server or fetching playlists.

_Configuration_
Server Address: `https://<mydomain>.duckdns.org/` (configured nginx reverse proxy and Let's Encrypt certificate)
Username: `PlexEmailAddress`
API key:  `MyPlexToken`

Testing with `https://<mydomain>.duckdns.org/?X-Plex-Token=<MyPlexToken>` works correctly

All other options give 300 (with different domain and/or with port forwarding)

Plex version is 1.32.7.7621 
The watch is Fenix 7 Pro Solar

**Comment by memen45** [comment]
Did you try without the trailing slash?

**Comment by lucasartori** [comment]
After removing the trailing slash from the address it connects but there are still problems

"Test Server" starts but does not complete; appears on the screen
- Inlog OK
- No podcasts
and remains still without proceeding further

Playlist browser works

Selecting playlists to sync works and I select a playlist with only 1 song

When launching synchronization it remains at 0% and "GarminSdkError::0" is displayed

Probably same problem as #84 ?

**Comment by memen45** [comment]
Plex doesn't have podcasts, so Test server is correct. The error during sync is most likely related to the SSL ciphers you have enabled on the server. See #42.

**Comment by lucasartori** [comment]
Even after changing the SSL ciphers like in #42 I still get the same "GarminSdkError::0" is displayed

![image](https://github.com/memen45/SubMusic/assets/20454862/66d5eba9-f1e0-4e32-bec5-ff4f5e6e2976)

**Comment by memen45** [comment]
Were you able to resolve this or is this still an issue for you?

**Comment by lucasartori** [comment]
I haven't been able to resolve it, it still fails.

**Comment by memen45** [comment]
Are you able to complete the connection with the SubMusic for Plex app? You can test the Plex connection without any payment. Also you can send debug info from the Settings => Plex => Servers => (Server Name) => Send Debug Info.

Do you happen to have any server logs?

The server address should be reachable from the wifi network that your watch connects to as well. During the Test Server option, the phone connection is still used, but during sync, the wifi network of the watch itself is used instead. You might have an issue with local vs remote Plex url which changes depending on whether your phone is connected or wifi.

**Comment by memen45** [comment]
Check #71 and #99, make sure to use `--key-type rsa` with the certbot command. Fenix 7 series does not support other certificates than RSA at the moment, and based on the enabled ciphers you sent, there is only ECDSA enabled. 

Did you manually change the certificates or is the Plex default certificate not working?

**Comment by memen45** [comment]
Closing because of lack of information. If there are updates, feel free to comment or reopen!
