### ISSUE TITLE
Add Support for Garmin vivoactive 5

### ISSUE THREAD

**Issue by KR-Law** [memen45/SubMusic#86]
The Vivoactive 5 uses API level 4.2.0.  So it should work as there are other devices. I tried adding it just like in issue #39 so I could submit a pull request but the master branch will not compile for me.

**Comment by KR-Law** [comment]
I determined why I could not build. I had to turn off typeCheckLevel. There are some type errors in the code. Submitted pull request.  #88

**Comment by memen45** [comment]
It is correct that type checking needs to be turned off for compilation. This is due to some shortcomings in the typing system of the Monkey C language.

**Comment by memen45** [comment]
Support should be added with 0.2.11. Will push the code shortly.

Also, I believe type check level to gradual works now as well. There are still some things the type checker does not understand in more strict level, so gradual is the highest for now.
