### ISSUE TITLE
no sync : NC-20.0.2, SubMusic-0.0.21, Fenix 6xPro

### ISSUE THREAD

**Issue by stefangweichinger** [memen45/SubMusic#9]
Sorry to say, but I don't get music synced for a few days now. The problems might be older already, I didn't use your music provider app for quite a while.

Maybe it's related to the RC-firmware of the Fenix6, I don't know, I only want to mention that.

Current situation:

I use the subsonic API, "test server" on the watch works fine. I can fetch and select playlists.
"sync" just does time out. It stands there at "0%" for some minutes, then fails.
Nothing in my nextcloud-logs. There *was* something around external user authentication, but I removed that app and its config, that error is gone, no difference in the behavior of SubMusic.

This was the situation before and after upgrading to 0.0.21 right now (dec 9, 10:15h)

**Comment by memen45** [comment]
Thanks a lot for reporting! I have received another report of this issue and I have not been able to solve it yet.

- Does it actually complete the sync or not (by looking at the songs in the playlist)? It might be just the progress that is not updated, but the sync is completed already in the background.
- Do you have errors on (some of) the songs on the playlist, thus having a 'needs sync' in the playlist overview?

**Comment by stefangweichinger** [comment]
I removed all but 3 files which were already on the watch. So the sync should be instant. Nothing, "0%" for minutes ...
No files "need sync" on the watch.

So I interpret this as "sync doesn't happen" ?

**Comment by memen45** [comment]
So after the sync if you open the Configure Playback, are all the songs still on the playlist? Thanks a lot for the feedback. I will try some things and hopefully update soon. It might take a couple of hours though, as I am still unsure of the cause and I want to implement your suggested improvement as well to make debugging easier for you.

**Comment by stefangweichinger** [comment]
No problem, no hurry. I have other things to do as well and also want to find the time for my running today ;-)

The files are on the watch, but right now playback starts and I don't *hear* anything on the BT buds.
This was now "solved" by rebooting the watch -> this is very likely a FW issue w/ "13.00 Public Release Candidate"
This is all rather frustrating ;-)

**Comment by memen45** [comment]
From your explanation I do not completely understand what problem remains and which was solved, let me know what you mean exactly.

Just now I released a new version that includes some potential fix for your problem. However, if it is not fixed, I think the problem is due to some bug in Connect IQ. Let me know your experience and if it still hangs, I will try another solution.

Looking forward to hearing from you!

**Comment by stefangweichinger** [comment]
Great improvement! More detail later.

**Comment by stefangweichinger** [comment]
Sync works now. Great. Quicker and reliable, I add stuff right now and retry, but it looks *good*
Also accessing sync vs. playback seems a bit better. It makes a difference if I go via Settings or directly via "hot key" (in case of F6 it's "long press down button". But way better, really!

An additional point (sorry ...): there seems to be an icon missing (or no matching icon available) on the F6:

When I chose "the hamburger" (three dots) in playback, between "random" and "volume" there is the menu point "SubMusic": it has no icon, so you have to know there is something ;-) 

... I will sync more files now, looks very promising now. *thanks*

**Comment by memen45** [comment]
After rereading some feedback from another developer I think I know the exact cause. There are actually two flows possible for sync

- ConfigureSync (from the Manage Music) -> Sync SubMusic 
- from anywhere else -> startSync()

I have to choose which of the two to support, cause as it seems now, I can only support one of the two at a time. 

There is also a third flow, which is initiated automatically e.g. when the watch is charging. I have no idea yet when that is working or when it's broken. If you have experience with this, please let me know! (If it is completed, you can check the menu again, the time of last sync should be updated)

Thanks a lot for testing!

**Comment by stefangweichinger** [comment]
So you suggest, that charging also triggers a sync? The whole fuzzing around used quite some battery today, so I have to charge the watch right now. I could put a new mp3 up there and see what happens ... ?

**Comment by memen45** [comment]
Yes! Well at least on my device, often the sync starts some time after connecting the watch to the charger. I don't think changing server side matters for the sync initiation, but it might make it easier for you to spot the update!

**Comment by stefangweichinger** [comment]
Charging ~20 minutes did not trigger a sync (checked by looking at the time of last sync on the watch).

Now I initiated a "manual" sync and see if the 2 new files come in. Right now it shows that "0% abgeschlossen".
I would like to see something like "2 files/205 MB to sync", if possible: that would show me as a user what the current task is, and it helps to judge the "amount of sync work". Just an idea. Maybe too detailed for the mainstream user .. but I assume most of the users aren't mainstream at all.

**Comment by stefangweichinger** [comment]
completely leaving the music app and restarting it via "long press down" seems to trigger another, different sync flow:

now I see "Synchronisieren" and a progress circle around it ... (I like this one better than the "0%")

This sync finished OK, and I can now play the 2 new files on the watch.

That's good. ;-)

Does that help you?

**Comment by stefangweichinger** [comment]
plus: now I plugged it into the charger again and that triggered a sync ... the one with the "0%" display ... seems to fail, as it takes minutes already / and there are no changed files in the nextcloud.

**Comment by memen45** [comment]
> completely leaving the music app and restarting it via "long press down" seems to trigger another, different sync flow:

Cannot reproduce this flow unfortunately. However I recognize that there are two possible sync screens. As a developer I do not have control over this. All I can do is set the percentage of completion and notify completion. These latter two do not always work apparently.

The newest SDK version supports more granular progress reporting for downloads, such that even during file download the progress can be updated. I will try and add this feature soon as it helps especially when downloading large files (podcasts).

**Comment by memen45** [comment]
> plus: now I plugged it into the charger again and that triggered a sync ... the one with the "0%" display ... seems to fail, as it takes minutes already / and there are no changed files in the nextcloud.

Can I conclude that the 0% version fails and the circle progress works? Or is it not related to success of the sync?

**Comment by stefangweichinger** [comment]
ok, I think I understand. One more and last note today: I did another "manual sync" now, via "long press down", "More ...", "Sync".
That works. 

What is a bit misleading: after that the menu point "Sync" is showing the timestamp of the last sync *before* that one, I have to leave and re-enter this menu to update that information. Maybe you can fix that? It's not a problem for me, but might lead to confusion.

Thanks a lot so far. Good night.

**Comment by stefangweichinger** [comment]
> Can I conclude that the 0% version fails and the circle progress works? Or is it not related to success of the sync?

Yes, I also think it's the case. "0%" fails, "circle" works.

**Comment by memen45** [comment]
> ok, I think I understand. One more and last note today: I did another "manual sync" now, via "long press down", "More ...", "Sync".
> That works. 

Ah, okay, long press down is 'library' or 'configure playback' on your device.

> What is a bit misleading: after that the menu point "Sync" is showing the timestamp of the last sync *before* that one, I have to leave and re-enter this menu to update that information. Maybe you can fix that? It's not a problem for me, but might lead to confusion.

Thanks a lot! Didn't know this screen is reverted to after the sync completed. I should be able to fix this quite easily.

Todo list:
[ ] Fix icon for Fenix6pro 
[ ] Granular progress during sync
[ ] Find solution for 0% sync fails (will be difficult)
[ ] Fix the last sync timestamp

**Comment by stefangweichinger** [comment]
Yeah, nice ;-)

Wait a bit maybe: Garmin just started rollout of System Software 13.10 for the Fenix6: https://forums.garmin.com/outdoor-recreation/outdoor-recreation/f/fenix-6-series/247979/system-software-13-10---rollout-in-progress

Maybe that changes something again.

**Comment by stefangweichinger** [comment]
So far things work for me, thanks.

An observation which might be Fenix-specific, just want to ask:

Does playback of music remember where you last stopped? For music this might not be relevant, for listening to podcasts it would be great if I could continue listening where I stopped yesterday. In my experience that is not the case right now. And with podcasts of multiple hours length this is kind of annoying. Try to fast forward 90 minutes on a watch while running :-P 

Do you think/know if this might be related to some "this file is new, because it synced today" or so? Or does the music player on the Garmin watches simply not track "playback position"?

**Comment by memen45** [comment]
Are all the syncing issues fixed? Or still the same hanging and working sync flows?

Do you mean tracking for multiple songs (podcasts) at the same time or just store the status of the player such that playing can be continued from the last session? Maybe it is better to make a separate issue for this, so I can close this one soon (update is on the way, including a warning when a possibly hanging sync flow is started).

**Comment by stefangweichinger** [comment]
Status: same as last week:

* 0% sync hangs (for example when triggered by charging)
* circle sync works ... when I do it manually. So I know my way around ...

tracking:

* new issue: yep, will do
* for sure it would be better to have it for multiple songs

**Comment by memen45** [comment]
> Todo list:
> 
>     * [ ]  Fix icon for Fenix6pro
> 
>     * [ ]  Granular progress during sync
> 
>     * [x]  Find solution for 0% sync fails (will be difficult)
> 
>     * [x]  Fix the last sync timestamp

**Comment by memen45** [comment]
> Todo list:
> 

- [ ]  Fix icon for Fenix6pro
- [x]  Granular progress during sync
- [x]  Find solution for 0% sync fails (will be difficult)
- [x]  Fix the last sync timestamp

As per version 0.1.0-alpha the granular sync progress update is included. Hope this helps. 
With regards to the missing icon: I have no idea what I can do about it right now, so will be fixed later.

**Comment by stefangweichinger** [comment]
feedback: last release breaks things for me, sorry

- test server: works
- sync fails

But it seems the watch has an issue with Wifi or BT, as others report for the current firmware (this also drains battery).

I restart it and retry sync: it takes a long time searching the Wifi-network ... and fails. 
"select playlists": brings a strange screen (half white, half black) ... and now things just hang, no wifi found, nothing possible.

hmm. Just to provide feedback.

**Comment by memen45** [comment]
Thanks a lot for your feedback and sorry to hear it is not working properly. The update indeed broke the Error reports, and that may be the cause of your half white half black screen. I have just now pushed an update (v0.1.1-bravo) which should fix it. Let me know if you are able to see error reports properly, it should help track down the problem with the watch as well.

**Comment by stefangweichinger** [comment]
had to reboot once again, after upgrading your package
Now I added a new file and was able to sync. nice.
