### ISSUE TITLE
[Garmin Venu 3] Subsonic Premium mandatory ?

### ISSUE THREAD

**Issue by shad-lp** [memen45/SubMusic#96]
Hello,

Firstly thanks for your hard, much appreciated.
Recently, I spinned up a Subsonic feature through docker, was working wonderfully until I get a Subsonic error code 60 on sync :

https://www.subsonic.org/pages/api.jsp

`The trial period for the Subsonic server is over. Please upgrade to Subsonic Premium. Visit subsonic.org for details`

Confirmed if I try to fetch playlists :

![PXL_20240713_173735018](https://github.com/user-attachments/assets/6e03f7e6-a7f0-4aa7-bf2f-f23e414bb9b4)

Maybe I'm missing where it is specified, but I didn't understand that Subsonic Premium was needed for your app.

Should I switch to a Subsonic API alternative ?

**Comment by memen45** [comment]
Subsonic premium is not required for SubMusic to work as far as I know. I suspect the docker image requires you to have subsonic premium?

You can use the available alternatives for subsonic (e.g. Airsonic-advanced or nextcloud+music) or use Ampache with the Ampache API. That API is much better and allows for larger playlists. 

If you happen to need a cloud storage alternative as well, I could recommend Nextcloud with the Music app. It supports Ampache API as well as Subsonic API (would recommend Ampache). 

Lastly, there is also [SubMusic for Plex](https://apps.garmin.com/en-US/apps/30c6b7ab-7fc8-4241-99f5-9872dfe56a73) which you can use with the [Plex Media Server](https://www.plex.tv/media-server-downloads/). It is the easiest to install and setup, but SubMusic for Plex is a paid app.

Hope this helps!

**Comment by shad-lp** [comment]
Thanks for your fast answer. Actually I'm using this image, the only one that is frequently maintained : https://hub.docker.com/r/stuckj/subsonic

I'll give a look at your suggestions. On the media server side, I'm using Emby, btw I've commented on your feature request concerning the Emby implementation.

**Comment by memen45** [comment]
Closed the issue, as it is not really an issue with regards to the SubMusic repository. You are free to discuss here further or send me a personal message (see Contact Developer option on the Garmin Connect app store).

**Comment by shad-lp** [comment]
Just for those who would face the same problem, Ampache does the job perfectly.
